#!/usr/bin/perl -w

my $erts_version=$ARGV[0];
my @files = `ls -d *\-*`;
chomp(@files);

my($filename);
foreach $filename (@files) {
        my($name) = $filename;
        print STDERR "Incorporating $filename:";

        #
        #  Add documentation directories
        #
        my(@info) = `ls $filename`;
        foreach $line (@info) {
                chomp($line);
                print STDERR " $line";
                print "/usr/share/doc/erlang-doc/html/lib/" . $filename . "/" . $line;
                print "  /usr/lib/erlang/lib/" . $filename . "/" . $line;
                print "\n";
        }
	print STDERR "\n";
}

#
#  Closing boilerplate
#
print "/usr/share/doc/erlang-doc/html/erts-$erts_version/doc /usr/lib/erlang/erts-$erts_version/doc\n";
print "/usr/share/doc/erlang-doc/html/doc /usr/lib/erlang/doc\n";

print STDERR "Finished generating erlang-doc.links\n";
